apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sudoku2
  name: sudoku2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudoku2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sudoku2
    spec:
      containers:
      - image: webcontiner.azurecr.io/webcontiner
        name: sudoku2
        ports:
        - containerPort: 80
        resources: {}
status: {}
