apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sudokuapp
  name: sudokuapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudokuapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sudokuapp
    spec:
      containers:
      - image: webcontiner.azurecr.io/sudokuapp2
        name: sudokuapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
