apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sudoku
  name: sudoku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudoku
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sudoku
    spec:
      containers:
      - image: webcontiner.azurecr.io/webcontiner
        name: sudoku
        ports:
        - containerPort: 80
        resources: {}
status: {}
